services:
  ultrafeeder:
    image: ghcr.io/sdr-enthusiasts/docker-adsb-ultrafeeder
    container_name: adsb-ultrafeeder
    hostname: adsb-ultrafeeder
    restart: unless-stopped
    
    # Privileged mode for USB access
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    
    ports:
      - "8080:80"          # Web interface
      - "30005:30005"      # Beast output
      - "30003:30003"      # SBS output
    
    environment:
      # Logging
      - LOGLEVEL=error
      - TZ=Asia/Singapore
      
      # SDR Configuration
      - READSB_DEVICE_TYPE=rtlsdr
      - READSB_RTLSDR_DEVICE=00000001
      - READSB_GAIN=auto
      - READSB_RTLSDR_PPM=0
      
      # Location (CHANGE THESE TO YOUR COORDINATES)
      - READSB_LAT=1.345073
      - READSB_LON=103.946810
      - READSB_ALT=30m
      
      # ADSB.lol Feed Configuration
      - ULTRAFEEDER_CONFIG=
          adsb,in.adsb.lol,30004,beast_reduce_plus_out;
          mlat,in.adsb.lol,31090,--lat,1.345073,--lon,103.946810,--alt,30,      mlat,in.adsb.lol,31090,--lat,1.345073,--lon,103.946810,--alt,30,--user,Singapore6441
      
      # Web interface settings
      - READSB_NET_API_PORT=30152
      - TAR1090_DEFAULTCENTERLAT=1.345073
      - TAR1090_DEFAULTCENTERLON=103.946810
      - TAR1090_DEFAULTZOOMLVL=8
      
      - UUID=87ae0f6b-a467-4a5c-9e27-b252c75dd769

    volumes:
      - adsb_data:/opt/adsb
      - adsb_history:/var/globe_history
      - adsb_collectd:/var/lib/collectd
    
    tmpfs:
      - /tmp:exec,size=64M
      - /var/log:size=32M

volumes:
  adsb_data:
  adsb_history:
  adsb_collectd: