version: '3.8'

services:
  readsb-data-collector:
    image: ghcr.io/sdr-enthusiasts/docker-readsb-protobuf:latest
    container_name: readsb-data-collector
    hostname: readsb-data-collector
    restart: unless-stopped
    
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    
    environment:
      - TZ=Asia/Singapore
      - READSB_DEVICE_TYPE=none
      - READSB_NET_ONLY=true
      - LOGLEVEL=error
      
      # Connect to ADSBExchange Beast feed
      - READSB_NET_CONNECTOR=out.adsb.lol,1365,beast_in
      
      # Location
      - READSB_LAT=1.345073
      - READSB_LON=103.946810
      - READSB_MAX_RANGE=999999
      
      # Network ports (use standard names)
      - READSB_NET_BEAST_OUTPUT_PORT=30105
      - READSB_NET_BEAST_INPUT_PORT=30104
      
      # JSON output
      - READSB_WRITE_JSON_EVERY=5
      - READSB_JSON_LOCATION_ACCURACY=2
      
      # Performance
      - READSB_STATS_EVERY=300
      - READSB_NET_HEARTBEAT=30
      - READSB_QUIET=true
      - READSB_ICAO_FILTER_SIZE=262144 # 4194304     
      
      # Disable web components
      - DISABLE_WEBAPP=true
      - TAR1090_DISABLE=true
    
    volumes:
      - readsb_data:/var/run/readsb
      - ./json_output:/run/readsb
    
    networks:
      - adsb_network

  beast-json-processor:
    image: node:18-alpine
    container_name: beast-json-processor
    depends_on:
      - readsb-data-collector
    restart: unless-stopped
    
    environment:
      - TZ=Asia/Singapore
      - NODE_ENV=production
    
    volumes:
      - ./beast-processor:/app
      - ./enhanced_json:/app/output
    
    working_dir: /app
    
    command: node beast-processor.js
    
    networks:
      - adsb_network

networks:
  adsb_network:
    driver: bridge

volumes:
  readsb_data: