version: '3.8'

services:
  readsb:
    image: mikenye/readsb-protobuf:latest
    container_name: readsb
    restart: unless-stopped
    environment:
      - READSB_NET_ONLY=true
      - READSB_NET_CONNECTOR=185.233.105.52,1337,beast_in  # Use IP directly
      - READSB_NET_BEAST_OUTPUT_PORT=30901
      - TZ=Asia/Singapore
    ports:
      - "30901:30901"  # Expose beast output port
    networks:
      - adsb_network

  beast-json-processor:
    image: node:18-alpine
    container_name: beast-json-processor
    restart: unless-stopped
    
    env_file:
      - ./beast-processor/.env
    
    environment:
      - TZ=Asia/Singapore
      - NODE_ENV=production
      - H3_RESOLUTION=8
    
    volumes:
      - ./beast-processor:/app
      - ./enhanced_json:/app/output
    
    working_dir: /app
    
    command: sh -c "npm install && npm start"
    
    networks:
      - adsb_network

networks:
  adsb_network:
    driver: bridge