services:
  beast-json-processor:
    image: node:18-alpine
    container_name: beast-json-processor
    restart: unless-stopped
    
    env_file:
      - ./beast-processor/.env
    
    environment:
      - TZ=Asia/Singapore
      - NODE_ENV=production
      - H3_RESOLUTION=3
      - BEAST_HOST=out.adsb.lol  # Connect directly to adsb.lol
      - BEAST_PORT=1365          # Same as readsb
    
    volumes:
      - ./beast-processor:/app
      - ./enhanced_json:/app/output
    
    working_dir: /app
    
    command: sh -c "sleep 10 && npm install && npm start"
    
    networks:
      - adsb_network

networks:
  adsb_network:
    driver: bridge